version: "3.9"
services:
  app:
    build: .
    image: "dimovskidev/redis_cdv"
    ports:
      - "3000:3000"
    environment:
      PORT: "3000"
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
